const ENVIRONNEMENTS = {
  BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  ENCRYPTION_KEY: process.env.NEXT_PUBLIC_ENCRYPTION_KEY,
  ENCRYPTION_API_KEY: process.env.NEXT_PUBLIC_ENCRYPTION_API_KEY,
  AES_IV: process.env.NEXT_PUBLIC_AES_IV,
  AES_SECRET_KEY: process.env.NEXT_PUBLIC_AES_SECRET_KEY,
};

export default ENVIRONNEMENTS;
