export const STORE_LOCATIONS = [
  { ville: "Abidjan", commune: "Cocody", quartier: "Riviera Palmeraie" },
  { ville: "Abidjan", commune: "Cocody", quartier: "Angré" },
  { ville: "Abidjan", commune: "Cocody", quartier: "Deux Plateaux" },
  { ville: "Abidjan", commune: "Marcory", quartier: "Zone 4" },
  { ville: "Abidjan", commune: "Marcory", quartier: "Biétry" },
  { ville: "Abidjan", commune: "Plateau", quartier: "Centre-ville" },
  { ville: "Abidjan", commune: "Yopougon", quartier: "Selmer" },
  { ville: "Abidjan", commune: "Yopougon", quartier: "Siporex" },
  { ville: "Abidjan", commune: "Yopougon", quartier: "Maroc" },
  { ville: "Abidjan", commune: "Treichville", quartier: "Gare" },
  { ville: "Abidjan", commune: "Abobo", quartier: "Marché" },
  { ville: "Abidjan", commune: "Abobo", quartier: "PK18" },
  { ville: "Abidjan", commune: "Adjamé", quartier: "Forum" },
  { ville: "Abidjan", commune: "Adjamé", quartier: "Liberté" },
  { ville: "Abidjan", commune: "Koumassi", quartier: "Remblais" },
  { ville: "Abidjan", commune: "Port-Bouët", quartier: "Vridi" },
  { ville: "Abidjan", commune: "Bingerville", quartier: "Centre" },
  { ville: "Abidjan", commune: "Songon", quartier: "Songon-Dagbé" },
  { ville: "Bouaké", commune: "Commerce", quartier: "Grand Marché" },
  { ville: "Bouaké", commune: "Koko", quartier: "Zone Résidentielle" },
  { ville: "Bouaké", commune: "Air France", quartier: "Centre" },
  { ville: "Yamoussoukro", commune: "Centre", quartier: "Habitat" },
  { ville: "Yamoussoukro", commune: "Morofé", quartier: "Zone 1" },
  { ville: "San-Pédro", commune: "Centre", quartier: "Lac" },
  { ville: "San-Pédro", commune: "Bardot", quartier: "Cité" },
  { ville: "Daloa", commune: "Commerce", quartier: "Grand Marché" },
  { ville: "Daloa", commune: "Huberson", quartier: "Centre" },
  { ville: "Korhogo", commune: "Centre", quartier: "Sinistré" },
  { ville: "Korhogo", commune: "Soba", quartier: "Zone Nord" },
  { ville: "Man", commune: "Centre", quartier: "Commerce" },
  { ville: "Gagnoa", commune: "Centre", quartier: "Résidentiel" },
  { ville: "Abengourou", commune: "Centre", quartier: "Marché" },
  { ville: "Divo", commune: "Centre", quartier: "Grand Marché" },
  { ville: "Séguéla", commune: "Centre", quartier: "Marché" },
  { ville: "Odienné", commune: "Centre", quartier: "Commerce" },
  { ville: "Bondoukou", commune: "Centre", quartier: "Zanzan" },
  { ville: "Ferkessédougou", commune: "Centre", quartier: "Gare" },
  { ville: "Agnibilékrou", commune: "Centre", quartier: "Marché" },
  { ville: "Adzopé", commune: "Centre", quartier: "Commerce" },
  { ville: "Grand-Bassam", commune: "Centre", quartier: "Quartier France" },
  { ville: "Dabou", commune: "Centre", quartier: "Lopou" },
  { ville: "Agboville", commune: "Centre", quartier: "Commerce" },
  { ville: "Sassandra", commune: "Centre", quartier: "Port" },
  { ville: "Issia", commune: "Centre", quartier: "Marché" },
  { ville: "Duékoué", commune: "Centre", quartier: "Commerce" },
  { ville: "Guiglo", commune: "Centre", quartier: "Centre" },
  { ville: "Soubré", commune: "Centre", quartier: "Marché" },
  { ville: "Oumé", commune: "Centre", quartier: "Commerce" },
  { ville: "Biankouma", commune: "Centre", quartier: "Centre" },
  { ville: "Touba", commune: "Centre", quartier: "Commerce" },
]
